controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

example:
    path: /api/example
    methods: GET
    defaults: { _controller: '\App\Controller\ExampleController::getExample' }